from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.graphics.shapes import Drawing
from reportlab.graphics.charts.piecharts import Pie
from reportlab.graphics.charts.legends import Legend
from io import BytesIO
from sqlalchemy.orm import Session
from app.db.models.user import User
from app.db.models.career import LearningPlan

def generate_career_passport(user: User, db: Session) -> BytesIO:
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()

    # Custom Styles
    title_style = styles['Title']
    title_style.textColor = colors.HexColor("#0f172a")

    h2_style = ParagraphStyle(
        'Heading2Custom',
        parent=styles['Heading2'],
        textColor=colors.HexColor("#008080"),
        spaceAfter=12
    )

    normal_style = styles['Normal']

    story = []

    # --- HEADER ---
    story.append(Paragraph(f"{user.name or 'User'}'s Career Strategy Report", title_style))
    story.append(Spacer(1, 12))
    story.append(Paragraph("Generated by CareerDev AI", normal_style))
    story.append(Spacer(1, 24))

    # --- SECTION 1: REALITY CHECK (CHART) ---
    story.append(Paragraph("1. Reality Check: Skill Distribution", h2_style))

    profile = user.career_profile
    if profile and profile.skills_graph_data:
        data_json = profile.skills_graph_data
        # Parse Chart.js format
        # {"labels": ["A", "B"], "datasets": [{"data": [10, 20]}]}
        labels = data_json.get("labels", [])
        datasets = data_json.get("datasets", [])

        if datasets:
            data_values = datasets[0].get("data", [])

            if data_values and sum(data_values) > 0:
                # Create Drawing
                d = Drawing(400, 200)

                # Pie/Doughnut
                pc = Pie()
                pc.x = 100
                pc.y = 50
                pc.width = 100
                pc.height = 100
                pc.data = data_values
                pc.labels = labels

                # Make it a doughnut (Simulated by Pie for now as innerRadius is not standard)
                # pc.innerRadius = 30

                # Colors
                # Default Chart.js colors mapped to Hex
                chart_colors = [
                    colors.HexColor("#00f3ff"), # Cyan
                    colors.HexColor("#bd00ff"), # Purple
                    colors.HexColor("#00ff88"), # Green
                    colors.HexColor("#ffff00"), # Yellow
                    colors.HexColor("#ff0055"), # Red
                    colors.gray
                ]

                for i, val in enumerate(data_values):
                    # Cycle through colors
                    pc.slices[i].fillColor = chart_colors[i % len(chart_colors)]
                    pc.slices[i].strokeColor = colors.white
                    pc.slices[i].strokeWidth = 1

                d.add(pc)

                # Legend
                legend = Legend()
                legend.alignment = 'right'
                legend.x = 250
                legend.y = 100
                legend.colorNamePairs = [(pc.slices[i].fillColor, labels[i]) for i in range(len(labels))]
                d.add(legend)

                story.append(d)
            else:
                 story.append(Paragraph("No skill data available to generate chart.", normal_style))
        else:
            story.append(Paragraph("No dataset found.", normal_style))
    else:
        story.append(Paragraph("Profile analysis not yet complete.", normal_style))

    story.append(Spacer(1, 24))

    # --- SECTION 2: MARKET SCORE ---
    story.append(Paragraph("2. Market Alignment Score", h2_style))

    score = profile.market_relevance_score if profile else 0
    score_text = f"<b>{score}/100</b>"

    # Simple Color Logic for Text
    color = "red"
    if score > 80: color = "green"
    elif score > 50: color = "orange"

    story.append(Paragraph(f"Current Relevance Score: <font color={color}>{score_text}</font>", normal_style))
    story.append(Paragraph("This score reflects the intersection between your GitHub activity and current market demand for high-value skills.", normal_style))
    story.append(Spacer(1, 24))

    # --- SECTION 3: ACTION PLAN ---
    story.append(Paragraph("3. Action Plan", h2_style))

    plan_items = []

    # 1. Primary: Pending Micro Projects
    if profile and profile.pending_micro_projects:
        for task in profile.pending_micro_projects:
            # Assuming task is dict: {'title': '...', 'status': '...'}
             if isinstance(task, dict) and task.get('status') != 'completed':
                 plan_items.append([task.get('title', 'Unknown Task'), "Pending"])

    # 2. Secondary: Learning Plan
    if not plan_items:
        learning_plans = db.query(LearningPlan).filter(
            LearningPlan.user_id == user.id,
            LearningPlan.status != 'completed'
        ).all()
        for lp in learning_plans:
            plan_items.append([lp.title, "Learning Goal"])

    # 3. Tertiary: Default
    if not plan_items:
        plan_items.append(["System Task: Complete your Profile Setup", "Critical"])

    # Render Table
    table_data = [["Task / Goal", "Type"]] + plan_items
    t = Table(table_data, colWidths=[4*inch, 2*inch])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#0f172a")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.whitesmoke),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
    ]))

    story.append(t)

    # Build
    doc.build(story)
    buffer.seek(0)
    return buffer
