from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image as PlatypusImage, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from io import BytesIO
import matplotlib.pyplot as plt

def generate_career_passport_pdf(user_name: str, reality_data: dict, alignment_score: int, action_plan: list) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []

    # Header
    story.append(Paragraph(f"{user_name} - Career Strategy Report", styles['Title']))
    story.append(Spacer(1, 12))

    # Section 1: Reality Check Chart
    # Create matplotlib chart
    plt.figure(figsize=(4, 4))
    labels = list(reality_data.keys())
    sizes = list(reality_data.values())
    plt.pie(sizes, labels=labels, autopct='%1.1f%%', startangle=140)
    plt.axis('equal')
    plt.title("Skills Reality Check")

    img_buffer = BytesIO()
    plt.savefig(img_buffer, format='png')
    img_buffer.seek(0)
    plt.close()

    story.append(Paragraph("1. Skills Reality Check", styles['Heading2']))
    story.append(PlatypusImage(img_buffer, width=300, height=300))
    story.append(Spacer(1, 12))

    # Section 2: Market Alignment Score
    story.append(Paragraph("2. Market Alignment Score", styles['Heading2']))
    story.append(Paragraph(f"Score: {alignment_score}/100", styles['BodyText']))
    story.append(Spacer(1, 12))

    # Section 3: Action Plan
    story.append(Paragraph("3. Action Plan (Kanban)", styles['Heading2']))
    data = [["Task Status", "Description"]]
    for task in action_plan:
        data.append([task.get('status', 'Todo'), task.get('title', 'Untitled')])

    t = Table(data)
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
    ]))
    story.append(t)
    story.append(Spacer(1, 24))

    # Footer
    story.append(Paragraph("Generated by CareerDev AI", styles['Italic']))

    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()
