"""add_missing_last_weekly_check

Revision ID: 03fad1d840ed
Revises: b07cc15ad068
Create Date: 2026-02-02 18:16:45.991322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03fad1d840ed'
down_revision: Union[str, Sequence[str], None] = 'b07cc15ad068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
