"""add last_weekly_check

Revision ID: 3ebf35ff1aba
Revises: b759033bec88
Create Date: 2026-02-03 00:39:18.001874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ebf35ff1aba'
down_revision: Union[str, Sequence[str], None] = 'b759033bec88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ml_risk_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'created_at')
    op.add_column('career_profiles', sa.Column('seniority', sa.String(length=20), nullable=True))
    op.add_column('career_profiles', sa.Column('primary_stack', sa.String(length=50), nullable=True))
    op.add_column('risk_snapshots', sa.Column('risk_level', sa.String(length=10), nullable=True))
    op.alter_column('risk_snapshots', 'risk_factor',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'last_weekly_check',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_column('users', 'address_country')
    op.drop_column('users', 'billing_address_number')
    op.drop_column('users', 'billing_address_state')
    op.drop_column('users', 'billing_address_country')
    op.drop_column('users', 'billing_address_complement')
    op.drop_column('users', 'billing_address_city')
    op.drop_column('users', 'address_city')
    op.drop_column('users', 'billing_address_street')
    op.drop_column('users', 'address_number')
    op.drop_column('users', 'address_zip_code')
    op.drop_column('users', 'address_complement')
    op.drop_column('users', 'billing_address_zip_code')
    op.drop_column('users', 'address_state')
    op.drop_column('users', 'address_street')
    op.drop_index(op.f('ix_weekly_routines_user_id'), table_name='weekly_routines')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_weekly_routines_user_id'), 'weekly_routines', ['user_id'], unique=False)
    op.add_column('users', sa.Column('address_street', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('address_state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('billing_address_zip_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('address_complement', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('address_zip_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('address_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('billing_address_street', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('address_city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('billing_address_city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('billing_address_complement', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('billing_address_country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('billing_address_state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('billing_address_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('address_country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('users', 'last_weekly_check',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('risk_snapshots', 'risk_factor',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('risk_snapshots', 'risk_level')
    op.drop_column('career_profiles', 'primary_stack')
    op.drop_column('career_profiles', 'seniority')
    op.add_column('audit_logs', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('ml_risk_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ml_risk', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rule_risk', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('final_risk', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('model_version', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('experiment_group', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('ml_risk_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ml_risk_logs_pkey'))
    )
    # ### end Alembic commands ###
