"""Add company and region to career_profiles

Revision ID: 7daa517ef830
Revises: b117589f198b
Create Date: 2026-02-06 22:03:11.334441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7daa517ef830'
down_revision: Union[str, Sequence[str], None] = 'b117589f198b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('career_profiles', sa.Column('company', sa.String(length=100), nullable=True))
    op.add_column('career_profiles', sa.Column('region', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('career_profiles', 'region')
    op.drop_column('career_profiles', 'company')
    # ### end Alembic commands ###
