"""Add team and organization to CareerProfile

Revision ID: a294b06baf5d
Revises: 7daa517ef830
Create Date: 2026-02-07 01:26:49.289937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a294b06baf5d'
down_revision: Union[str, Sequence[str], None] = '7daa517ef830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('career_profiles', sa.Column('organization', sa.String(length=100), nullable=True))
    op.add_column('career_profiles', sa.Column('team', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('career_profiles', 'team')
    op.drop_column('career_profiles', 'organization')
    # ### end Alembic commands ###
